#ifndef __ERRCODES_H__
#define __ERRCODES_H__

#define FAILED_ALLOC_ERROR -1
#define EMPTY_FILE_ERROR -2
#define READ_FILE_ERROR -3
#define UNEXPECTED_EOF_EROR -4
#define INVALID_INPUT_ERROR -5
#define INVALID_SIZE_ERROR -6
#define INVALID_ELEM_ERROR -7
#define ELEM_EXISTS_ERROR -8
#define SIZE_OVERFLOW_ERROR -9
#define CHAIN_OVERFLOW_ERROR -10
#define WRONG_CHECK_ERROR -11
#define INPUT_ZERO_ERROR -12
#define LT_ERROR -13
#define NZNLT_ERROR -14
#define CANT_OPEN_FILE_ERROR -15
#define INVALID_SIZES_ERROR -16
#define WRONG_USAGE_ERROR -17
#define MATRICES_SIZES_ERROR -18
#define INCOMPATIBLE_SLAE_ERROR -19

#endif // __ERRCODES_H__
