#ifndef __ERRCODES_H__
#define __ERRCODES_H__

#define SUCCESS								 0
#define FAILED_ALLOC_ERROR					-1
#define EMPTY_INPUT_FILE_ERROR				-2
#define UNEXPECTED_EOF_ERROR				-3
#define INVALID_COUNTRY_NAME_ERROR			-4
#define INVALID_POPULATION_ERROR			-5
#define INVALID_CAPITAL_ERROR				-6
#define INVALID_CONTINENT_ERROR				-7
#define INVALID_TOURISM_ERROR				-8
#define INVALID_TOURISM_DATA_ERROR			-9
#define INVALID_OBJECTS_ERROR				-10
#define INVALID_EXCURSION_BASIC_ERROR		-11
#define INVALID_SEASON_ERROR				-12
#define INVALID_TEMP_ERROR					-13
#define INVALID_FLIGHT_TIME_ERROR			-14
#define INVALID_SPORTS_BASIC_ERROR			-15
#define INVALID_MIN_COST_ERROR				-16
#define INVALID_INPUT_TEXT_FILE_ERROR		-20

#endif // __ERRCODES_H__
