#ifndef __ERRCODES_H__
#define __ERRCODES_H__

#define SUCCESS 0
#define WRONG_USAGE_ERROR -1
#define EMPTY_STRING_ERROR -2
#define INVALID_STRING_ERROR -3
#define BUF_OVERFLOW_ERROR -4
#define MANTISSA_OVERFLOW_ERROR -5
#define EXPONENT_OVERFLOW_ERROR -6
#define NOT_INT_ERROR -7
#define MULTIPLY_OVERFLOW_ERROR -8

#endif // __ERRCODES_H__
